### ISSUE TITLE
[Feature] Automatically add entry to Windows Terminal window selector

### ISSUE THREAD

**Issue by PinkDev1** [redcode-labs/easyWSL#14]
For me, the settings file was on `C:\Users\%USERNAME%\AppData\Local\Packages\Microsoft.WindowsTerminal_8wekyb3dbbwe\localState\settings.json`. It would only be necesarry to add an entry under `"list"` like this:

```json
,
{
    "commandline": "wsl -d %DISTRONAME%",
    "guid": "%AUTO-GENERATED-GUID%",
    "hidden": false,
    "icon": "%easyWSL-ICON-PATH%",
    "name": "%DISTRONAME-CAPITALISED%"
}
```

Where AUTO-GENERATED-GUID can be generated with:[[1]](https://traviscolbert.net/blog/windows-terminal-generating-guids-for-your-profiles/)
```powershell
[guid]::NewGuid()
```

I'd make a PR but I don't know csharp 😅

**Comment by PinkDev1** [comment]
nvm I opened this issue before testing the tool

**Comment by unrooted** [comment]
No problem, hope you'll enjoy using our tool
