### ISSUE TITLE
[feature] hope support image.tar file 

### ISSUE THREAD

**Issue by wuxingzhong** [redcode-labs/easyWSL#15]
## example 

```bash
docker save -o images.tar alpine:latest 
```
hope can support  Specify  images.tar  file  as a docker image.

**Comment by dhanar10** [comment]
+1

**Comment by wrobeljakub** [comment]
So you would like to be be able to import an existing rootfs obtained from docker by `docker save -o images.tar alpine:latest ` command. Am I right?

**Comment by dhanar10** [comment]
Yes

**Comment by wrobeljakub** [comment]
It is possible and very easy to implement. However we don't see much value in integrating it.  `wsl.exe` already has the import function and we use it in easyWSL to register distros. You can read more about this on that MS docs page. https://docs.microsoft.com/en-us/windows/wsl/use-custom-distro

**Comment by wuxingzhong** [comment]
ok, thanks!
