### ISSUE TITLE
post-install script is failing

### ISSUE THREAD

**Issue by scadu** [redcode-labs/easyWSL#17]
While playing with the easyWSL I noticed that the post-install script doesn't work correctly.

Examples:

* Arch Linux:
```
A number of a distro you want to install: 1
A name for your distro (default ArchLinux):
A path to a directory where you want to store your distro (default is C:\Users\easywsl\AppData\Local\easyWSL\distros\ArchLinux):
Downloading 1. layer ...
Downloading 2. layer ...
Creating install.tar file ...
Registering the distro ...
Cleaning up ...
/mnt/c/Users/easywsl/Downloads/Release/post-install.sh: line 1: ﻿echo: command not found
/mnt/c/Users/easywsl/Downloads/Release/post-install.sh: line 34: syntax error near unexpected token `$'\r''
'mnt/c/Users/easywsl/Downloads/Release/post-install.sh: line 34: `add_user()
```

* Alpine Linux, where Bash and shadow aren't available by default:
```
A number of a distro you want to install: 4
A name for your distro (default Alpine):
A path to a directory where you want to store your distro (default is C:\Users\easywsl\AppData\Local\easyWSL\distros\Alpine):
Downloading 1. layer ...
Creating install.tar file ...
Registering the distro ...
Cleaning up ...
/mnt/c/Users/easywsl/Downloads/Release/post-install.sh: line 1: ﻿echo: not found
/mnt/c/Users/easywsl/Downloads/Release/post-install.sh: line 64: syntax error: unexpected word (expecting "in")
```

**Comment by mikenelson-io** [comment]
This is still an issue. The new post-install.sh file is also erroring.
ArchLinux:
![image](https://user-images.githubusercontent.com/6254544/132720338-ccd335f4-3416-420b-b59a-32c579bb1263.png)

**Comment by scadu** [comment]
Looks like there's another `post-install.sh` in the `Release` directory which as I can see was generated during the build process, committed to the repository. I guess it's time to think about a CI/CD pipeline 😄.

**Comment by unrooted** [comment]
Okay, I see. Still, thanks for your PR @scadu!
We basically have to do some code cleaning up soon... we will do it with the next release (while also adding other features, stay tuned).

**Comment by mikenelson-io** [comment]
I copy/pasted the raw content of the post-install.sh that is located in the root of easyWSL/easyWSL/. That was the one recently modified. It has the addition of  `#!/usr/bin/env sh` in line 1. Is that not the correct file?

**Comment by scadu** [comment]
@mikenelson-io Indeed, it's a correct file. I'll provide a fix in another PR.

**Comment by scadu** [comment]
@mikenelson-io I checked the script once again, and it works correctly. For some reason, I ignored that you copied the script focusing on the mysterious `No such file or directory` for `/usr/bin/env`. 
While copying, line endings have changed from `LF` (*nix) to `CRLF` (Windows) resulting in a file that's not interpreted correctly by the *nix shell. If you copy the script and save the file with the `LF` line endings, it should be better (VSCode, Notepad++ provide option to change the file line endings easily).
cc @unrooted

**Comment by mikenelson-io** [comment]
I just slapped myself for not seeing that 🤦 
Thank you for clarifying!

**Comment by unrooted** [comment]
Thanks, @scadu, for helping us with the post install script. We've cleaned up the project and the corrected the line endings too. You can build the master branch and see if it works as intended.  We are planning to make a new release soon, but before that we want to test everything pretty extensively.
If that's doable, can you please guys check whether it works right now, after the latest update when you build from the source code yourselves?

**Comment by scadu** [comment]
@unrooted Is it possible to add a build procedure to the readme? I wouldn't like to guess trying to work out a correct setup.
