### ISSUE TITLE
Can't open settings page.

### ISSUE THREAD

**Issue by dingdang66686** [redcode-labs/easyWSL#24]
The program crashed when clicking the settings icon. Please solve this bug.
System information:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/42102822/163709037-6043de24-e597-4246-b996-1732932c1730.png">

**Comment by unrooted** [comment]
Have you built the package yourself or have you used the one provided as a Release file or have you downloaded easyWSL directly from the MS Store?

**Comment by dingdang66686** [comment]
I just download directly from the release page.

**Comment by unrooted** [comment]
Firstly, make sure you have WSL turned on as a feature.

If doable, get easyWSL directly from Microsoft Store. 
However, the package available as a Release file, is a .msix signed by Microsoft, which is basically the same thing, as in Store, so I dunno what might be the cause of the issue, if not turned off WSL.

Given the fact that you use Windows 11, I can provide you with unsigned .msix, which is our dev build (Win11 allows installing unsigned packages in Dev mode easily, without making a fuss about it, as it sometimes used to do on Win10) in case nothing works. I can also guide you through changing Execution Policies and turning on Dev mode on your Win machine.
You can email me if you're interested.

**Comment by unrooted** [comment]
Closing this issue due to the inactivity. Please reach out to us if the problem still persists.
