### ISSUE TITLE
[Bug] Manage distributions list is always empty

### ISSUE THREAD

**Issue by Luk164** [redcode-labs/easyWSL#28]
Manage distributions list is always empty. (See screenshot)

![image](https://user-images.githubusercontent.com/30559213/195063780-77521e50-9aae-4616-9794-c91fb8baed16.png)

Proof that I have distros installed:

![image](https://user-images.githubusercontent.com/30559213/195063922-9dc71f1a-05ed-4ad4-bd94-62fdb89e2921.png)

Some of the distros were created via easyWSL.

**Comment by Luk164** [comment]
MS Store

**Comment by unrooted** [comment]
Okay, that is weird for sure. Pulled a new one on fresh VM and worked like a charm. Can you please try either the GitHub release or building it yourself?

**Comment by Luk164** [comment]
Sure, once I get back home

**Comment by Luk164** [comment]
@unrooted  Installing from github release worked. I the uninstalled it and reinstalled the MS Store version and it also worked. I have no idea what might have caused the issue.

**Comment by unrooted** [comment]
Thanks, great to hear that.

We sometimes hear about issues that we've never even encountered on none of our build nor within any of our VMs, so I'm not really that surprised you had issue of the same kind.

Hope you're enjoying easyWSL, feel free to contribute. It's nice seeing people actually using it, thanks for that. Have a great day!
