### ISSUE TITLE
Crash on startup.

### ISSUE THREAD

**Issue by flexxxxer** [redcode-labs/easyWSL#29]
.NET 6 installed, WSL too. How i can help?

**Comment by unrooted** [comment]
Hi, thanks for reporting this bug.

Do you have developer mode enabled on your system? Have you tried building easyWSL yourself, or have you got it off GitHub releases or from Microsoft Store?

**Comment by flexxxxer** [comment]
Yes, developer mode enabled on my system. I tried to use it from Microsoft Store - not working, tried from github releases package - not working. OS is Windows 11.

**Comment by unrooted** [comment]
That is weird because it works perfectly fine on my fresh VM. Can you please try building it yourself and see if the issue persists?

**Comment by flexxxxer** [comment]
Yes. Here what i get:
![image](https://user-images.githubusercontent.com/44833369/196548362-c89c66fd-f0b7-4a0f-bbf4-b6d15230bfc9.png)

**Comment by Git-North** [comment]
Having the same problem, 
Installed via microsoft store 
dotnet installed

**Comment by unrooted** [comment]
Hello all of you, 

I've just installed version from MS Store to confirm whether issue still persists. Happily, it doesn't, at least not on my current system which is Win11 with all of the required .NET thingies (including those required for building, hence, hard to tell whether it's just a matter of fact to install "just" .NET runtime, or additional libraries required for building as well)

Please reach out to us if the issue still persists.

**Comment by unrooted** [comment]
What I'd try is trying to install additional deps which I mention alongside it all. 

As said, hard to say what *might* be missing, due to my current dev setup, but then I guess you can be 100% sure you've elimated problems related to dependencies.
