### ISSUE TITLE
What URL for 'release page'?

### ISSUE THREAD

**Issue by hsmyers** [redcode-labs/easyWSL#6]
The readme says:

`Just go to our release page, download latest release and just run it. Done!`

What is the URL as it seems to lead to endless loops otherwise.

**Comment by unrooted** [comment]
Hi! 
The release page can be found [here](https://github.com/redcode-labs/easyWSL/releases)

And you can download the latest release [here](https://github.com/redcode-labs/easyWSL/releases/download/1.1/easyWSL_Release-1.1.zip)
