### ISSUE TITLE
Cannot install Elementary OS 6

### ISSUE THREAD

**Issue by khuongduybui** [redcode-labs/easyWSL#7]
Hi devs, first of all, AWESOME work so far!!!

OK, let's cut to the chase. I want to install Elementary OS 6, which is from the docker image: `elementary/docker:odin-unstable`.

The code linked below only supports `:tag` for library/ images and `:latest` for namespaced images.

https://github.com/redcode-labs/easyWSL/blob/1698bc66cd644473801b85c02becae4244758683/easyWSL/DistroInstaller.cs#L95-L108

**Comment by unrooted** [comment]
Hi! Thanks for kind words and reporting this bug to us!
@KernelErr0r fixed that in #11 
You can download the latest release [here](https://github.com/redcode-labs/easyWSL/releases/tag/1.2)

I've tried that Docker Image which you've meant, but it feels... weird
![image](https://user-images.githubusercontent.com/30440603/129899808-061675d7-e3b5-44d2-a3f3-68cd99e50d83.png)

As you can see, it successfully is registered, but...

![image](https://user-images.githubusercontent.com/30440603/129899842-211074af-e506-4428-b68a-aaf5592ace1c.png)
I don't know what happens in here, I can't tell what causes that, but, as you can see, you get access to Elementary repos and `apt` is working, which is confirmed with `neofetch` installation. I don't know if those are correct Elementary repos for Odin, I'm not an expert on Elementary, but I guess it works *somehow*

Feel free to tell us about any other issues if you encounter them. Thanks for reporting that bug again.
