### ISSUE TITLE
Error mounting one of the file systems. Run 'dmesg' for more details.

### ISSUE THREAD

**Issue by lisandrocarmona** [redcode-labs/easyWSL#8]
I manage to install manjaro on wsl2 with kernel 5.10 but I'm not being able to run it.
At this point, how can I proceed? Thank you very much.

C:\Users\user>wsl -l
Windows Subsystem Distributions for Linux:
Manjaro (Default)

C:\Users\user>wsl Manjaro
Error mounting one of the file systems. Run 'dmesg' for more details.

**Comment by unrooted** [comment]
At the time of making, Manjaro was working perfectly fine. 
But I've noticed the same error, but, what's even funnier, this can happen even while using official MS Store WSL distros, according to what I've found on the internet. Some experienced this when upgrading to Win11, some experienced this without doing so. I'll investigate further, and please, tell me if you find any workaround.

**Comment by unrooted** [comment]
Due to (most likely) errors of one specific distro, I'm closing this issue as of right now. During my testing right now I didn't see any other distros doing the same. Please reach out to us if the issue still persists.
